wip: u.case

diff --git a/cmd/case/main0 b/cmd/case/main0
--- a/cmd/case/main0
+++ b/cmd/case/main0
@@ -2,6 +2,7 @@
 
 set -eu
 
+### -d: case directory ###
 d= F=0
 for c
 do shift
@@ -15,6 +16,7 @@ if test -z "$d"; then err 'u.case: -d is not set'; fi
 e mkdir -p "$d"
 if test ! -d "$d"; then err "u.case: fail to create directory '$d'"; fi
 
+### -f: file ###
 copy () {
     if test ! -r "$f"; then err "u.case: not a file '$f'"; fi
     e cp "$f" "$d"
@@ -24,6 +26,49 @@ for c
 do shift
    if   test "$c" = -f; then F=1
    elif test  $F -eq 1; then f="$c"; copy; F=0
+   else                      set -- "$@" "$c"
+   fi
+done
+
+exe () (
+    cd "$d"
+    e "$e"
+    if test $? -ne 0; then e 'u.case: fail to run "$e"'; fi
+)
+
+### -b: before ###
+e= F=0
+for c
+do shift
+   if   test "$c" = -b; then F=1
+   elif test  $F -eq 1; then e="$c"; exe; F=0
+   else                      set -- "$@" "$c"
+   fi
+done
+
+main () (
+    ### skip -a ###
+    local e c F
+    e= F=0
+    for c
+    do shift
+       if   test "$c" = -a; then F=1
+       elif test  $F -eq 1; then F=0
+       else                      set -- "$@" "$c"
+       fi
+    done
+    cd "$d"
+    e u.build "$@"
+    if test $? -ne 0; then err 'u.build failed'; fi
+)
+main "$@"
+
+### -a: after ###
+e= F=0
+for c
+do shift
+   if   test "$c" = -a; then F=1
+   elif test  $F -eq 1; then e="$c"; exe; F=0
    else                      set -- "$@" "$c"
    fi
 done
