remove unused part of u.doc.deps

diff --git a/doc/tools/deps b/doc/tools/deps
--- a/doc/tools/deps
+++ b/doc/tools/deps
@@ -2,35 +2,18 @@
 
 set -eu
 
+. u.doc.util
+
 usg() {
-    echo "usg: u.doc.deps [FILE.adoc].. > deps.mk"
+    msg 'usg: u.doc.deps [FILE.adoc].. > deps.mk'
     exit 0
 }
 
 if test $# -ne 0 && test "$1" = -h; then usg; fi
 
-make_path() {
-    dir="$1"; shift
-    for f
-    do echo "${dir}/$f"
-    done
-}
-
-filter_deps() {
-    for i
-    do if echo "$i" | grep "adoc"
-       then echo "$i"
-       fi
-    done
-}
-
-deps() {
-    for f
-    do target="${f%.adoc}.html"
-       DEPS=`u.doc.inc "$f" | sort | xargs`
-       if test $? -ne 0; then echo >&2 'u.doc.inc failed'; exit 2; fi
-       echo "$target: $f $DEPS"
-    done
-}
-
-deps "$@"
+for f
+do target="${f%.adoc}.html"
+   DEPS=`u.doc.inc "$f" | sort | xargs`
+   if test $? -ne 0; then echo >&2 'u.doc.inc failed'; exit 2; fi
+   echo "$target: $f $DEPS"
+done
