check input

diff --git a/cmd/utest/unpack b/cmd/utest/unpack
--- a/cmd/utest/unpack
+++ b/cmd/utest/unpack
@@ -10,5 +10,16 @@ usg () {
 }
 
 if test $# -ne 0 && test "$1" = -h; then usg; fi
+if test $# -eq 0; then err 'missing argument DIR'; fi
+
+d="$1"; shift
+if test ! -d "$d"; then err 'not a directory "$d"'; fi
+if test $# -eq 0; then err 'missing argument FILE'; fi
+
+for i
+do if ! test -f "$i"
+   then err "not a file '$i'"
+   fi
+done
 
 exec $prog0 "$@"
