check for geomview

diff --git a/poc/geomview/punto b/poc/geomview/punto
--- a/poc/geomview/punto
+++ b/poc/geomview/punto
@@ -4,6 +4,7 @@ prog=poc/geomview/punto
 . u.conf.util
 
 : ${AWK=awk}
+: ${GEOMVIEW=geomview}
 
 offp() {
     "$AWK" '{ if ("" $0 != "OFF") exit 1; else exit 0 }' "$1"
@@ -11,6 +12,10 @@ offp() {
 
 if test $# -ne 1
 then err 'needs OFF'
+fi
+
+if ! e "$GEOMVIEW" --version '2>/dev/null' '1>/dev/null'
+then err "$GOEMVIEW is not found"
 fi
 
 off="$1"; shift
@@ -34,4 +39,4 @@ cat >$t <<!
 }
 !
 
-geomview -noinit -nopanels -b 1 1 1  -run ./punto0 "$t"
+e "${GEOMVIEW}" -noinit -nopanels -b 1 1 1  -run ./punto0 "$t"
