correct trap in tsdf

diff --git a/tsdf/tsdf b/tsdf/tsdf
--- a/tsdf/tsdf
+++ b/tsdf/tsdf
@@ -1,12 +1,15 @@
 #!/bin/bash
 
 # A wrapper to tsdf.awk
-# Creates and deletes temporary directory
 
 t=/tmp/tsdf.$$
-mkdir -p $t
+if ! mkdir $t
+then
+    echo >&2 "tsdf: fail to create dir '$t'"
+    exit 2
+fi
 
-trap `rm -rf $t; exit 2` 1 2 3 15
+trap 'rm -rf $t; exit 2' 1 2 3 15
 TD=$t tsdf.awk -- "$@"
 
 rm -rf $t
